services:
  - type: web
    name: mini-stories-web
    env: node
    plan: free
    rootDir: apps/web
    buildCommand: |
      npm install
      npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_FUNCTIONS_URL
        sync: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_ENV
        value: production
    autoDeploy: true
    ports:
      - port: 3000
        protocol: http
